d = input('Digite algo: ')
print('O tipo primitivo é', type(d))
print('Contém apenas espaços? ', d.isspace())
print('É um número? ', d.isnumeric())
print('É alfabético? ', d.isalpha())
print('É alfanumérico? ', d.isalnum())
print('Está maiúsculo? ', d.isupper())
print('Está minúsculo? ', d.islower())
print('Está capitalizada? ', d.istitle())
